---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by BestDog07
--- DateTime: 2024/11/6 23:30
---
function Bind(componentTable,luaFunctionTable)
    for k,v in pairs(componentTable) do
        local st,ed = string.find(k,"button")
        if(st ~= nil and ed == string.len(k))  then
            local funcName = "on"..k.."click"
            local func = luaFunctionTable[funcName]
            if(func ~= nil) then
                componentTable[k].onClick:AddListener(luaFunctionTable[funcName])
                print("bind succeed")
            else
                print("Can Find Component but Func is nil")
                print(k .."    ".. funcName)
            end
            goto continue
        end
        st,ed = string.find(k,"slider")

        if(st ~= nil and ed == string.len(k))  then
            local funcName = "on"..k.."valuechanged"
            local func = componentTable[funcName]
            if(func ~= nil) then
                componentTable[k].onValueChanged:AddListener(luaFunctionTable[funcName])
                print("bind succeed")
            else
                print("Can Find Component but Func is nil")
                print(k .."    ".. funcName)
            end
            goto continue
        end
        ::continue::
    end
end